services:


  mysql:  # 数据库docker容器
    image: mysql:8.0
    container_name: lhmy_mysql
    restart: always  # 自动重启
    ports:
      - "3303:3306"  # 端口映射
    environment:
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: database
      TZ: Asia/Shanghai
    volumes:
      - "./dockerenvs/mysql/data:/var/lib/mysql"
      - "./dockerenvs/mysql/conf.d:/etc/mysql/conf.d"
      - "./dockerenvs/mysql/logs:/logs"
    privileged: true
    networks:
      - my_networks



networks:
  my_networks:
    driver: bridge